apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoyo
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: yoyo-contianer
        image: nginx:1.14.2
        ports:
        - containerPort: 80