apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    name: frontend-yoyo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
